### PR TITLE
CrashlyticsとAnalytics追加 

### LINKED ISSUE #120: CrashlyticsとAnalytics追加
## Overview
CrashlyticsとAnalyticsを追加する

### PR DESCRIPTION
**Pull request by kosenda**
## Issue
fix #120

## Overview
- CrashlyticsとAnalyticsを追加した

### CODE REVIEW

File: app/src/main/java/ksnd/hiraganaconverter/view/Application.kt [hunk 1]
```diff
@@ -1,6 +1,9 @@
 package ksnd.hiraganaconverter.view
```
Comment (KSNDBOT) [inline app/src/main/java/ksnd/hiraganaconverter/view/Application.kt:1]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/kosenda/hiragana-converter/blob/e6840731d6d7a56d11f88738ff6547aa68d4b22d/app/src/main/java/ksnd/hiraganaconverter/view/Application.kt#L1"></span>File must end with a newline (\n)</td>
    </tr>
  </tbody>
</table>
